version: "3.2"

services:
  app:
    build:
      context: docker/app
    volumes:
      - ".:/srv/www"
    tty: true
    networks:
      - filewatcher
networks:
  filewatcher:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 112.221.0.1/24